import {test,expect} from '@playwright/test';
const backend='http://127.0.0.1:19219';
const headers={'X-Hermes-Session-Token':'agent-native-local-e2e-only'};
test('cadence starts a separate attempt that revises saved work from Plane feedback',async({page,request})=>{
  test.setTimeout(90000);
  await page.addInitScript(()=>{window.__HERMES_SESSION_TOKEN__='agent-native-local-e2e-only';});
  await request.put(`${backend}/__e2e__/plane-config`,{headers,data:{enabled:true}});
  const created=await request.post(`${backend}/api/agent-native/agents`,{headers,data:{request_id:crypto.randomUUID(),name:'Continuing writer',purpose:'Revise drafts using feedback. E2E_CADENCE',work:{timeout_seconds:180,max_iterations:12}}});
  expect(created.status()).toBe(201);
  const {id}=await created.json();const api=`${backend}/api/agent-native/agents/${id}`;
  expect((await request.post(`${api}/cadence`,{headers,data:{expected_revision:1,enabled:false,interval_seconds:60}})).ok()).toBe(true);
  const current=async()=>(await(await request.get(api,{headers})).json());
  try{
    await expect.poll(async()=>(await current()).work.state,{timeout:30000}).toBe('completed');
    const first=(await current()).work;
    await request.post(`${backend}/__e2e__/comment/${id}`,{headers});
    await page.goto(`/agents/${id}`);
    const overview=page.getByRole('region',{name:'Current work overview',exact:true});
    await expect(overview).toContainText('Stage: Automatic work off');
    await expect(overview).toContainText('Latest attempt: completed');
    await expect(page.getByRole('link',{name:'Full view'})).toBeVisible();
    const planeLink=page.getByRole('link',{name:'Open project in Plane'});
    const settingsButton=page.getByRole('button',{name:'Agent settings'});
    await settingsButton.hover();
    await expect(page.getByRole('tooltip',{name:'Agent settings'})).toBeVisible();
    await planeLink.hover();
    await expect(page.getByRole('tooltip',{name:'Open project in Plane'})).toBeVisible();
    await settingsButton.click();
    const settings=page.getByRole('dialog',{name:'Agent settings'});
    await expect(settings).toBeVisible();
    const cadence=settings.getByRole('region',{name:'Thinking cadence',exact:true});
    await cadence.getByLabel('Check-in interval (seconds)').fill('60');
    await cadence.getByRole('button',{name:'Enable or update cadence'}).click();
    await expect(cadence).toContainText('Enabled · every 60 seconds');
    await expect(page.getByLabel('Execution status')).toHaveText('Active · waiting for next check-in');
    await cadence.getByLabel('Check-in interval (seconds)').fill('2');
    await cadence.getByRole('button',{name:'Enable or update cadence'}).click();
    await expect(cadence).toContainText('Enabled · every 2 seconds');
    await expect.poll(async()=>{const a=await current();return a.work.id!==first.id&&a.work.state==='completed';},{timeout:30000}).toBe(true);
    await cadence.getByRole('button',{name:'Disable cadence'}).click();
    await expect(cadence).toContainText('Automatic check-ins are off');
    await expect(cadence).toContainText('Automatic check-ins disabled. This agent will not start new work on its own.');
    await page.getByRole('button',{name:'Close'}).click();
    await expect(page.getByLabel('Execution status')).toHaveText('Automatic work off');
    const latest=(await current()).work;
    expect(latest.session_id).not.toBe(first.session_id);
    expect(latest.outputs.some((o:{version:number})=>o.version===2)).toBe(true);
    const output=latest.outputs.find((o:{version:number})=>o.version===2);
    const saved=await(await request.get(`${api}/outputs/${output.output_id}/versions/2`,{headers})).json();
    expect(saved.content).toContain('Initial cadence draft.');
    expect(saved.content).toContain('Revised after Plane feedback.');
    const history=await(await request.get(`${api}/attempts`,{headers})).json();
    expect(history).toHaveLength(2);
    const proof=await(await request.get(`${backend}/__e2e__/writer-evidence/${id}`,{headers})).json();
    expect(proof.comments.some((c:{comment_html:string})=>c.comment_html.includes('Saved a revision using your feedback.'))).toBe(true);
  }finally{await request.post(`${api}/work/pause`,{headers});}
});
